name = "carbide"
main = "src/carbide.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2025-02-08"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


kv_namespaces = [
    { binding = "CARBIDE", id = "<YOUR_KV_NAMESPACE_ID>" }
]
