name: Fetch and Upload K3s Images and Files

on:
  push:
    branches: [ "main" ]

jobs:
  k3s-fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        repo_version:
        - v1.32.1+k3s1
        - v1.31.5+k3s1
        - v1.30.9+k3s1
        - v1.29.13+k3s1
        - v1.28.3+k3s1
        - v1.27.7+k3s1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup ORAS
        uses: oras-project/setup-oras@v1
      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - name: hauler images
        run: |
          cat <<EOF > k3s-manifest.yaml
          apiVersion: content.hauler.cattle.io/v1alpha1
          kind: Images
          metadata:
            name: k3s-images-${{ matrix.repo_version }}
          spec:
            images:
          $(curl -sSfL https://github.com/k3s-io/k3s/releases/download/${{ matrix.repo_version }}/k3s-images.txt | sed 's/^/    - name: /')
          ---
          apiVersion: content.hauler.cattle.io/v1alpha1
          kind: Files
          metadata:
            name: k3s-files-${{ matrix.repo_version }}
          spec:
            files:
              - path: https://github.com/k3s-io/k3s/releases/download/${{ matrix.repo_version }}/k3s
                name: k3s
              - path: https://github.com/k3s-io/k3s/releases/download/${{ matrix.repo_version }}/k3s-arm64
                name: k3s-arm64
              - path: https://github.com/k3s-io/k3s/releases/download/${{ matrix.repo_version }}/k3s-armhf
                name: k3s-armhf
              - path: https://github.com/k3s-io/k3s/releases/download/${{ matrix.repo_version }}/k3s-airgap-images-amd64.tar.zst
                name: k3s-airgap-images-amd64.tar.zst
              - path: https://github.com/k3s-io/k3s/releases/download/${{ matrix.repo_version }}/k3s-airgap-images-arm.tar.zst
                name: k3s-airgap-images-arm.tar.zst
              - path: https://github.com/k3s-io/k3s/releases/download/${{ matrix.repo_version }}/k3s-airgap-images-arm64.tar.zst
                name: k3s-airgap-images-arm64.tar.zst
          EOF
      - name: load to GitHub Container Registry
        run: |
          REPO_VERSION=${{ matrix.repo_version }}
          MANIFEST_VERSION="${REPO_VERSION//+/-}"
          echo ${{ secrets.GITHUB_TOKEN }} | oras login --username ${{ github.repository_owner }} --password-stdin ghcr.io
          oras push ghcr.io/${{ steps.string.outputs.lowercase }}/hauler/k3s-manifest.yaml:$MANIFEST_VERSION k3s-manifest.yaml