name: Fetch and Upload Rancher Images and Charts

on:
  push:
    branches: [ "main" ]

jobs:
  rancher-fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        repo_version:
        - 2.10.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup ORAS
        uses: oras-project/setup-oras@v1
      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - uses: azure/setup-helm@v4.2.0
      - name: hauler images
        run: |
            helm repo add jetstack https://charts.jetstack.io
            helm repo update
            helmVersion=v1.16.3
            helmImages=$(helm template jetstack/cert-manager --version=${helmVersion} | grep 'image:' | sed 's/"//g; s/.*image: //' | sed 's/^/    - name: /')
            cat <<EOF > rancher-manifest.yaml
            apiVersion: content.hauler.cattle.io/v1alpha1
            kind: Charts
            metadata:
              name: rancher-airgap-charts
            spec:
              charts:
                - name: cert-manager
                  repoURL: https://charts.jetstack.io
                  version: ${helmVersion}
                - name: rancher
                  repoURL: https://releases.rancher.com/server-charts/latest
                  version: ${{ matrix.repo_version }}
            ---
            apiVersion: content.hauler.cattle.io/v1alpha1
            kind: Images
            metadata:
                name: cert-manager-airgap-images
            spec:
                images:
            ${helmImages}
            ---
            apiVersion: content.hauler.cattle.io/v1alpha1
            kind: Images
            metadata:
                name: rancher-airgap-images
            spec:
                images:
            $(curl -sSfL https://github.com/rancher/rancher/releases/download/${{ matrix.repo_version }}/rancher-images.txt | sed 's/^/    - name: /')
            EOF
      - name: load to GitHub Container Registry
        run: |
          REPO_VERSION=${{ matrix.repo_version }}
          MANIFEST_VERSION="${REPO_VERSION//+/-}"
          echo ${{ secrets.GITHUB_TOKEN }} | oras login --username ${{ github.repository_owner }} --password-stdin ghcr.io
          oras push ghcr.io/${{ steps.string.outputs.lowercase }}/hauler/rancher-manifest.yaml:$MANIFEST_VERSION rancher-manifest.yaml